# Generated by Django 3.0.6 on 2020-05-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('name', models.TextField()),
                ('chapter', models.TextField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
