# Generated by Django 3.0.6 on 2020-05-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('name', models.TextField()),
                ('question', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='test',
            name='question',
        ),
    ]
