# Generated by Django 3.0.6 on 2020-05-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20200529_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='questions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.TextField(),
        ),
    ]
