# Generated by Django 3.0.6 on 2020-06-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20200530_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='answers',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='choices',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='questionScores',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='test',
            name='answers',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='test',
            name='choices',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='test',
            name='questionScores',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='test',
            name='userScores',
            field=models.TextField(default='0'),
        ),
    ]
