# Generated by Django 3.0.6 on 2020-06-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20200601_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
