# Generated by Django 3.0.6 on 2020-06-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_test_iscompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='userPercentage',
            field=models.FloatField(default=0),
        ),
    ]
